/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.my_digi_id.acapy_client.invoker.JSON;


/**
 * DIDEndpointWithType
 */
@JsonPropertyOrder({
  DIDEndpointWithType.JSON_PROPERTY_DID,
  DIDEndpointWithType.JSON_PROPERTY_ENDPOINT,
  DIDEndpointWithType.JSON_PROPERTY_ENDPOINT_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-08T11:11:35.214106+01:00[Europe/Berlin]")
public class DIDEndpointWithType {
  public static final String JSON_PROPERTY_DID = "did";
  private String did;

  public static final String JSON_PROPERTY_ENDPOINT = "endpoint";
  private String endpoint;

  /**
   * Endpoint type to set (default &#39;Endpoint&#39;); affects only public or posted DIDs
   */
  public enum EndpointTypeEnum {
    ENDPOINT("Endpoint"),
    
    PROFILE("Profile"),
    
    LINKEDDOMAINS("LinkedDomains");

    private String value;

    EndpointTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EndpointTypeEnum fromValue(String value) {
      for (EndpointTypeEnum b : EndpointTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENDPOINT_TYPE = "endpoint_type";
  private EndpointTypeEnum endpointType;


  public DIDEndpointWithType did(String did) {
    this.did = did;
    return this;
  }

   /**
   * DID of interest
   * @return did
  **/
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv", required = true, value = "DID of interest")
  @JsonProperty(JSON_PROPERTY_DID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDid() {
    return did;
  }


  @JsonProperty(JSON_PROPERTY_DID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDid(String did) {
    this.did = did;
  }


  public DIDEndpointWithType endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Endpoint to set (omit to delete)
   * @return endpoint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://myhost:8021", value = "Endpoint to set (omit to delete)")
  @JsonProperty(JSON_PROPERTY_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndpoint() {
    return endpoint;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }


  public DIDEndpointWithType endpointType(EndpointTypeEnum endpointType) {
    this.endpointType = endpointType;
    return this;
  }

   /**
   * Endpoint type to set (default &#39;Endpoint&#39;); affects only public or posted DIDs
   * @return endpointType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Endpoint", value = "Endpoint type to set (default 'Endpoint'); affects only public or posted DIDs")
  @JsonProperty(JSON_PROPERTY_ENDPOINT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EndpointTypeEnum getEndpointType() {
    return endpointType;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointType(EndpointTypeEnum endpointType) {
    this.endpointType = endpointType;
  }


  /**
   * Return true if this DIDEndpointWithType object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DIDEndpointWithType diDEndpointWithType = (DIDEndpointWithType) o;
    return Objects.equals(this.did, diDEndpointWithType.did) &&
        Objects.equals(this.endpoint, diDEndpointWithType.endpoint) &&
        Objects.equals(this.endpointType, diDEndpointWithType.endpointType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(did, endpoint, endpointType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DIDEndpointWithType {\n");
    sb.append("    did: ").append(toIndentedString(did)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    endpointType: ").append(toIndentedString(endpointType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

