/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.my_digi_id.acapy_client.invoker.JSON;


/**
 * SchemasCreatedResult
 */
@JsonPropertyOrder({
  SchemasCreatedResult.JSON_PROPERTY_SCHEMA_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-08T11:11:35.214106+01:00[Europe/Berlin]")
public class SchemasCreatedResult {
  public static final String JSON_PROPERTY_SCHEMA_IDS = "schema_ids";
  private List<String> schemaIds = null;


  public SchemasCreatedResult schemaIds(List<String> schemaIds) {
    this.schemaIds = schemaIds;
    return this;
  }

  public SchemasCreatedResult addSchemaIdsItem(String schemaIdsItem) {
    if (this.schemaIds == null) {
      this.schemaIds = new ArrayList<>();
    }
    this.schemaIds.add(schemaIdsItem);
    return this;
  }

   /**
   * Get schemaIds
   * @return schemaIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSchemaIds() {
    return schemaIds;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaIds(List<String> schemaIds) {
    this.schemaIds = schemaIds;
  }


  /**
   * Return true if this SchemasCreatedResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemasCreatedResult schemasCreatedResult = (SchemasCreatedResult) o;
    return Objects.equals(this.schemaIds, schemasCreatedResult.schemaIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemasCreatedResult {\n");
    sb.append("    schemaIds: ").append(toIndentedString(schemaIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

