/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.my_digi_id.acapy_client.model.DIFProofRequest;
import com.my_digi_id.acapy_client.model.IndyProofRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.my_digi_id.acapy_client.invoker.JSON;


/**
 * V20PresRequestByFormat
 */
@JsonPropertyOrder({
  V20PresRequestByFormat.JSON_PROPERTY_DIF,
  V20PresRequestByFormat.JSON_PROPERTY_INDY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-08T11:11:35.214106+01:00[Europe/Berlin]")
public class V20PresRequestByFormat {
  public static final String JSON_PROPERTY_DIF = "dif";
  private DIFProofRequest dif;

  public static final String JSON_PROPERTY_INDY = "indy";
  private IndyProofRequest indy;


  public V20PresRequestByFormat dif(DIFProofRequest dif) {
    this.dif = dif;
    return this;
  }

   /**
   * Presentation request for DIF
   * @return dif
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Presentation request for DIF")
  @JsonProperty(JSON_PROPERTY_DIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DIFProofRequest getDif() {
    return dif;
  }


  @JsonProperty(JSON_PROPERTY_DIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDif(DIFProofRequest dif) {
    this.dif = dif;
  }


  public V20PresRequestByFormat indy(IndyProofRequest indy) {
    this.indy = indy;
    return this;
  }

   /**
   * Presentation request for indy
   * @return indy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Presentation request for indy")
  @JsonProperty(JSON_PROPERTY_INDY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IndyProofRequest getIndy() {
    return indy;
  }


  @JsonProperty(JSON_PROPERTY_INDY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndy(IndyProofRequest indy) {
    this.indy = indy;
  }


  /**
   * Return true if this V20PresRequestByFormat object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V20PresRequestByFormat v20PresRequestByFormat = (V20PresRequestByFormat) o;
    return Objects.equals(this.dif, v20PresRequestByFormat.dif) &&
        Objects.equals(this.indy, v20PresRequestByFormat.indy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dif, indy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V20PresRequestByFormat {\n");
    sb.append("    dif: ").append(toIndentedString(dif)).append("\n");
    sb.append("    indy: ").append(toIndentedString(indy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

