/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ibm.ssi.acapy_client.invoker.JSON;


/**
 * AdminStatusLiveliness
 */
@JsonPropertyOrder({
  AdminStatusLiveliness.JSON_PROPERTY_ALIVE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-28T08:24:27.640452+02:00[Europe/Berlin]")
public class AdminStatusLiveliness {
  public static final String JSON_PROPERTY_ALIVE = "alive";
  private Boolean alive;


  public AdminStatusLiveliness alive(Boolean alive) {
    this.alive = alive;
    return this;
  }

   /**
   * Liveliness status
   * @return alive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Liveliness status")
  @JsonProperty(JSON_PROPERTY_ALIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAlive() {
    return alive;
  }


  @JsonProperty(JSON_PROPERTY_ALIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlive(Boolean alive) {
    this.alive = alive;
  }


  /**
   * Return true if this AdminStatusLiveliness object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminStatusLiveliness adminStatusLiveliness = (AdminStatusLiveliness) o;
    return Objects.equals(this.alive, adminStatusLiveliness.alive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alive);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminStatusLiveliness {\n");
    sb.append("    alive: ").append(toIndentedString(alive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

