/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ibm.ssi.acapy_client.model.SignatureOptions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ibm.ssi.acapy_client.invoker.JSON;


/**
 * Doc
 */
@JsonPropertyOrder({
  Doc.JSON_PROPERTY_CREDENTIAL,
  Doc.JSON_PROPERTY_OPTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-28T08:24:27.640452+02:00[Europe/Berlin]")
public class Doc {
  public static final String JSON_PROPERTY_CREDENTIAL = "credential";
  private Object credential;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  private SignatureOptions options;


  public Doc credential(Object credential) {
    this.credential = credential;
    return this;
  }

   /**
   * Credential to sign
   * @return credential
  **/
  @ApiModelProperty(required = true, value = "Credential to sign")
  @JsonProperty(JSON_PROPERTY_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getCredential() {
    return credential;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCredential(Object credential) {
    this.credential = credential;
  }


  public Doc options(SignatureOptions options) {
    this.options = options;
    return this;
  }

   /**
   * Signature options
   * @return options
  **/
  @ApiModelProperty(required = true, value = "Signature options")
  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignatureOptions getOptions() {
    return options;
  }


  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOptions(SignatureOptions options) {
    this.options = options;
  }


  /**
   * Return true if this Doc object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Doc doc = (Doc) o;
    return Objects.equals(this.credential, doc.credential) &&
        Objects.equals(this.options, doc.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credential, options);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Doc {\n");
    sb.append("    credential: ").append(toIndentedString(credential)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

