/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ibm.ssi.acapy_client.model.IndyProofReqAttrSpecNonRevoked;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ibm.ssi.acapy_client.invoker.JSON;


/**
 * IndyProofReqAttrSpec
 */
@JsonPropertyOrder({
  IndyProofReqAttrSpec.JSON_PROPERTY_NAME,
  IndyProofReqAttrSpec.JSON_PROPERTY_NAMES,
  IndyProofReqAttrSpec.JSON_PROPERTY_NON_REVOKED,
  IndyProofReqAttrSpec.JSON_PROPERTY_RESTRICTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-28T08:24:27.640452+02:00[Europe/Berlin]")
public class IndyProofReqAttrSpec {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NAMES = "names";
  private List<String> names = null;

  public static final String JSON_PROPERTY_NON_REVOKED = "non_revoked";
  private JsonNullable<IndyProofReqAttrSpecNonRevoked> nonRevoked = JsonNullable.<IndyProofReqAttrSpecNonRevoked>undefined();

  public static final String JSON_PROPERTY_RESTRICTIONS = "restrictions";
  private List<Map<String, String>> restrictions = null;


  public IndyProofReqAttrSpec name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Attribute name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "favouriteDrink", value = "Attribute name")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public IndyProofReqAttrSpec names(List<String> names) {
    this.names = names;
    return this;
  }

  public IndyProofReqAttrSpec addNamesItem(String namesItem) {
    if (this.names == null) {
      this.names = new ArrayList<>();
    }
    this.names.add(namesItem);
    return this;
  }

   /**
   * Attribute name group
   * @return names
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attribute name group")
  @JsonProperty(JSON_PROPERTY_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getNames() {
    return names;
  }


  @JsonProperty(JSON_PROPERTY_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNames(List<String> names) {
    this.names = names;
  }


  public IndyProofReqAttrSpec nonRevoked(IndyProofReqAttrSpecNonRevoked nonRevoked) {
    this.nonRevoked = JsonNullable.<IndyProofReqAttrSpecNonRevoked>of(nonRevoked);
    return this;
  }

   /**
   * Get nonRevoked
   * @return nonRevoked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public IndyProofReqAttrSpecNonRevoked getNonRevoked() {
        return nonRevoked.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NON_REVOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<IndyProofReqAttrSpecNonRevoked> getNonRevoked_JsonNullable() {
    return nonRevoked;
  }
  
  @JsonProperty(JSON_PROPERTY_NON_REVOKED)
  public void setNonRevoked_JsonNullable(JsonNullable<IndyProofReqAttrSpecNonRevoked> nonRevoked) {
    this.nonRevoked = nonRevoked;
  }

  public void setNonRevoked(IndyProofReqAttrSpecNonRevoked nonRevoked) {
    this.nonRevoked = JsonNullable.<IndyProofReqAttrSpecNonRevoked>of(nonRevoked);
  }


  public IndyProofReqAttrSpec restrictions(List<Map<String, String>> restrictions) {
    this.restrictions = restrictions;
    return this;
  }

  public IndyProofReqAttrSpec addRestrictionsItem(Map<String, String> restrictionsItem) {
    if (this.restrictions == null) {
      this.restrictions = new ArrayList<>();
    }
    this.restrictions.add(restrictionsItem);
    return this;
  }

   /**
   * If present, credential must satisfy one of given restrictions: specify schema_id, schema_issuer_did, schema_name, schema_version, issuer_did, cred_def_id, and/or attr::&lt;attribute-name&gt;::value where &lt;attribute-name&gt; represents a credential attribute name
   * @return restrictions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If present, credential must satisfy one of given restrictions: specify schema_id, schema_issuer_did, schema_name, schema_version, issuer_did, cred_def_id, and/or attr::<attribute-name>::value where <attribute-name> represents a credential attribute name")
  @JsonProperty(JSON_PROPERTY_RESTRICTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Map<String, String>> getRestrictions() {
    return restrictions;
  }


  @JsonProperty(JSON_PROPERTY_RESTRICTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestrictions(List<Map<String, String>> restrictions) {
    this.restrictions = restrictions;
  }


  /**
   * Return true if this IndyProofReqAttrSpec object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndyProofReqAttrSpec indyProofReqAttrSpec = (IndyProofReqAttrSpec) o;
    return Objects.equals(this.name, indyProofReqAttrSpec.name) &&
        Objects.equals(this.names, indyProofReqAttrSpec.names) &&
        Objects.equals(this.nonRevoked, indyProofReqAttrSpec.nonRevoked) &&
        Objects.equals(this.restrictions, indyProofReqAttrSpec.restrictions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, names, nonRevoked, restrictions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndyProofReqAttrSpec {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    nonRevoked: ").append(toIndentedString(nonRevoked)).append("\n");
    sb.append("    restrictions: ").append(toIndentedString(restrictions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

