/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ibm.ssi.acapy_client.invoker.JSON;


/**
 * V20CredFilterIndy
 */
@JsonPropertyOrder({
  V20CredFilterIndy.JSON_PROPERTY_CRED_DEF_ID,
  V20CredFilterIndy.JSON_PROPERTY_ISSUER_DID,
  V20CredFilterIndy.JSON_PROPERTY_SCHEMA_ID,
  V20CredFilterIndy.JSON_PROPERTY_SCHEMA_ISSUER_DID,
  V20CredFilterIndy.JSON_PROPERTY_SCHEMA_NAME,
  V20CredFilterIndy.JSON_PROPERTY_SCHEMA_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-11T17:04:23.656276+02:00[Europe/Berlin]")
public class V20CredFilterIndy {
  public static final String JSON_PROPERTY_CRED_DEF_ID = "cred_def_id";
  private String credDefId;

  public static final String JSON_PROPERTY_ISSUER_DID = "issuer_did";
  private String issuerDid;

  public static final String JSON_PROPERTY_SCHEMA_ID = "schema_id";
  private String schemaId;

  public static final String JSON_PROPERTY_SCHEMA_ISSUER_DID = "schema_issuer_did";
  private String schemaIssuerDid;

  public static final String JSON_PROPERTY_SCHEMA_NAME = "schema_name";
  private String schemaName;

  public static final String JSON_PROPERTY_SCHEMA_VERSION = "schema_version";
  private String schemaVersion;


  public V20CredFilterIndy credDefId(String credDefId) {
    this.credDefId = credDefId;
    return this;
  }

   /**
   * Credential definition identifier
   * @return credDefId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv:3:CL:20:tag", value = "Credential definition identifier")
  @JsonProperty(JSON_PROPERTY_CRED_DEF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCredDefId() {
    return credDefId;
  }


  @JsonProperty(JSON_PROPERTY_CRED_DEF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredDefId(String credDefId) {
    this.credDefId = credDefId;
  }


  public V20CredFilterIndy issuerDid(String issuerDid) {
    this.issuerDid = issuerDid;
    return this;
  }

   /**
   * Credential issuer DID
   * @return issuerDid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv", value = "Credential issuer DID")
  @JsonProperty(JSON_PROPERTY_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuerDid() {
    return issuerDid;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerDid(String issuerDid) {
    this.issuerDid = issuerDid;
  }


  public V20CredFilterIndy schemaId(String schemaId) {
    this.schemaId = schemaId;
    return this;
  }

   /**
   * Schema identifier
   * @return schemaId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv:2:schema_name:1.0", value = "Schema identifier")
  @JsonProperty(JSON_PROPERTY_SCHEMA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaId() {
    return schemaId;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaId(String schemaId) {
    this.schemaId = schemaId;
  }


  public V20CredFilterIndy schemaIssuerDid(String schemaIssuerDid) {
    this.schemaIssuerDid = schemaIssuerDid;
    return this;
  }

   /**
   * Schema issuer DID
   * @return schemaIssuerDid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv", value = "Schema issuer DID")
  @JsonProperty(JSON_PROPERTY_SCHEMA_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaIssuerDid() {
    return schemaIssuerDid;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaIssuerDid(String schemaIssuerDid) {
    this.schemaIssuerDid = schemaIssuerDid;
  }


  public V20CredFilterIndy schemaName(String schemaName) {
    this.schemaName = schemaName;
    return this;
  }

   /**
   * Schema name
   * @return schemaName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "preferences", value = "Schema name")
  @JsonProperty(JSON_PROPERTY_SCHEMA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaName() {
    return schemaName;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaName(String schemaName) {
    this.schemaName = schemaName;
  }


  public V20CredFilterIndy schemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Schema version
   * @return schemaVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.0", value = "Schema version")
  @JsonProperty(JSON_PROPERTY_SCHEMA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaVersion() {
    return schemaVersion;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
  }


  /**
   * Return true if this V20CredFilterIndy object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V20CredFilterIndy v20CredFilterIndy = (V20CredFilterIndy) o;
    return Objects.equals(this.credDefId, v20CredFilterIndy.credDefId) &&
        Objects.equals(this.issuerDid, v20CredFilterIndy.issuerDid) &&
        Objects.equals(this.schemaId, v20CredFilterIndy.schemaId) &&
        Objects.equals(this.schemaIssuerDid, v20CredFilterIndy.schemaIssuerDid) &&
        Objects.equals(this.schemaName, v20CredFilterIndy.schemaName) &&
        Objects.equals(this.schemaVersion, v20CredFilterIndy.schemaVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credDefId, issuerDid, schemaId, schemaIssuerDid, schemaName, schemaVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V20CredFilterIndy {\n");
    sb.append("    credDefId: ").append(toIndentedString(credDefId)).append("\n");
    sb.append("    issuerDid: ").append(toIndentedString(issuerDid)).append("\n");
    sb.append("    schemaId: ").append(toIndentedString(schemaId)).append("\n");
    sb.append("    schemaIssuerDid: ").append(toIndentedString(schemaIssuerDid)).append("\n");
    sb.append("    schemaName: ").append(toIndentedString(schemaName)).append("\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

