/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ibm.ssi.acapy_client.model.V20CredExRecord;
import com.ibm.ssi.acapy_client.model.V20CredExRecordIndy;
import com.ibm.ssi.acapy_client.model.V20CredExRecordLDProof;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ibm.ssi.acapy_client.invoker.JSON;


/**
 * V20CredExRecordDetail
 */
@JsonPropertyOrder({
  V20CredExRecordDetail.JSON_PROPERTY_CRED_EX_RECORD,
  V20CredExRecordDetail.JSON_PROPERTY_INDY,
  V20CredExRecordDetail.JSON_PROPERTY_LD_PROOF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-28T08:24:27.640452+02:00[Europe/Berlin]")
public class V20CredExRecordDetail {
  public static final String JSON_PROPERTY_CRED_EX_RECORD = "cred_ex_record";
  private V20CredExRecord credExRecord;

  public static final String JSON_PROPERTY_INDY = "indy";
  private V20CredExRecordIndy indy;

  public static final String JSON_PROPERTY_LD_PROOF = "ld_proof";
  private V20CredExRecordLDProof ldProof;


  public V20CredExRecordDetail credExRecord(V20CredExRecord credExRecord) {
    this.credExRecord = credExRecord;
    return this;
  }

   /**
   * Credential exchange record
   * @return credExRecord
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Credential exchange record")
  @JsonProperty(JSON_PROPERTY_CRED_EX_RECORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public V20CredExRecord getCredExRecord() {
    return credExRecord;
  }


  @JsonProperty(JSON_PROPERTY_CRED_EX_RECORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredExRecord(V20CredExRecord credExRecord) {
    this.credExRecord = credExRecord;
  }


  public V20CredExRecordDetail indy(V20CredExRecordIndy indy) {
    this.indy = indy;
    return this;
  }

   /**
   * Get indy
   * @return indy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INDY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public V20CredExRecordIndy getIndy() {
    return indy;
  }


  @JsonProperty(JSON_PROPERTY_INDY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndy(V20CredExRecordIndy indy) {
    this.indy = indy;
  }


  public V20CredExRecordDetail ldProof(V20CredExRecordLDProof ldProof) {
    this.ldProof = ldProof;
    return this;
  }

   /**
   * Get ldProof
   * @return ldProof
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LD_PROOF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public V20CredExRecordLDProof getLdProof() {
    return ldProof;
  }


  @JsonProperty(JSON_PROPERTY_LD_PROOF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLdProof(V20CredExRecordLDProof ldProof) {
    this.ldProof = ldProof;
  }


  /**
   * Return true if this V20CredExRecordDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V20CredExRecordDetail v20CredExRecordDetail = (V20CredExRecordDetail) o;
    return Objects.equals(this.credExRecord, v20CredExRecordDetail.credExRecord) &&
        Objects.equals(this.indy, v20CredExRecordDetail.indy) &&
        Objects.equals(this.ldProof, v20CredExRecordDetail.ldProof);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credExRecord, indy, ldProof);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V20CredExRecordDetail {\n");
    sb.append("    credExRecord: ").append(toIndentedString(credExRecord)).append("\n");
    sb.append("    indy: ").append(toIndentedString(indy)).append("\n");
    sb.append("    ldProof: ").append(toIndentedString(ldProof)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

