/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ibm.ssi.acapy_client.invoker.JSON;


/**
 * V20CredExRecordByFormat
 */
@JsonPropertyOrder({
  V20CredExRecordByFormat.JSON_PROPERTY_CRED_ISSUE,
  V20CredExRecordByFormat.JSON_PROPERTY_CRED_OFFER,
  V20CredExRecordByFormat.JSON_PROPERTY_CRED_PROPOSAL,
  V20CredExRecordByFormat.JSON_PROPERTY_CRED_REQUEST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-28T08:24:27.640452+02:00[Europe/Berlin]")
public class V20CredExRecordByFormat {
  public static final String JSON_PROPERTY_CRED_ISSUE = "cred_issue";
  private Object credIssue;

  public static final String JSON_PROPERTY_CRED_OFFER = "cred_offer";
  private Object credOffer;

  public static final String JSON_PROPERTY_CRED_PROPOSAL = "cred_proposal";
  private Object credProposal;

  public static final String JSON_PROPERTY_CRED_REQUEST = "cred_request";
  private Object credRequest;


  public V20CredExRecordByFormat credIssue(Object credIssue) {
    this.credIssue = credIssue;
    return this;
  }

   /**
   * Get credIssue
   * @return credIssue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRED_ISSUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCredIssue() {
    return credIssue;
  }


  @JsonProperty(JSON_PROPERTY_CRED_ISSUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredIssue(Object credIssue) {
    this.credIssue = credIssue;
  }


  public V20CredExRecordByFormat credOffer(Object credOffer) {
    this.credOffer = credOffer;
    return this;
  }

   /**
   * Get credOffer
   * @return credOffer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRED_OFFER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCredOffer() {
    return credOffer;
  }


  @JsonProperty(JSON_PROPERTY_CRED_OFFER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredOffer(Object credOffer) {
    this.credOffer = credOffer;
  }


  public V20CredExRecordByFormat credProposal(Object credProposal) {
    this.credProposal = credProposal;
    return this;
  }

   /**
   * Get credProposal
   * @return credProposal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRED_PROPOSAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCredProposal() {
    return credProposal;
  }


  @JsonProperty(JSON_PROPERTY_CRED_PROPOSAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredProposal(Object credProposal) {
    this.credProposal = credProposal;
  }


  public V20CredExRecordByFormat credRequest(Object credRequest) {
    this.credRequest = credRequest;
    return this;
  }

   /**
   * Get credRequest
   * @return credRequest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRED_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCredRequest() {
    return credRequest;
  }


  @JsonProperty(JSON_PROPERTY_CRED_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredRequest(Object credRequest) {
    this.credRequest = credRequest;
  }


  /**
   * Return true if this V20CredExRecordByFormat object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V20CredExRecordByFormat v20CredExRecordByFormat = (V20CredExRecordByFormat) o;
    return Objects.equals(this.credIssue, v20CredExRecordByFormat.credIssue) &&
        Objects.equals(this.credOffer, v20CredExRecordByFormat.credOffer) &&
        Objects.equals(this.credProposal, v20CredExRecordByFormat.credProposal) &&
        Objects.equals(this.credRequest, v20CredExRecordByFormat.credRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credIssue, credOffer, credProposal, credRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V20CredExRecordByFormat {\n");
    sb.append("    credIssue: ").append(toIndentedString(credIssue)).append("\n");
    sb.append("    credOffer: ").append(toIndentedString(credOffer)).append("\n");
    sb.append("    credProposal: ").append(toIndentedString(credProposal)).append("\n");
    sb.append("    credRequest: ").append(toIndentedString(credRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

