/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.ibm.ssi.acapy_client.invoker.JSON;


/**
 * VCRecord
 */
@JsonPropertyOrder({
  VCRecord.JSON_PROPERTY_CONTEXTS,
  VCRecord.JSON_PROPERTY_CRED_TAGS,
  VCRecord.JSON_PROPERTY_CRED_VALUE,
  VCRecord.JSON_PROPERTY_EXPANDED_TYPES,
  VCRecord.JSON_PROPERTY_GIVEN_ID,
  VCRecord.JSON_PROPERTY_ISSUER_ID,
  VCRecord.JSON_PROPERTY_PROOF_TYPES,
  VCRecord.JSON_PROPERTY_RECORD_ID,
  VCRecord.JSON_PROPERTY_SCHEMA_IDS,
  VCRecord.JSON_PROPERTY_SUBJECT_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-11T17:04:23.656276+02:00[Europe/Berlin]")
public class VCRecord {
  public static final String JSON_PROPERTY_CONTEXTS = "contexts";
  private List<String> contexts = null;

  public static final String JSON_PROPERTY_CRED_TAGS = "cred_tags";
  private Map<String, String> credTags = null;

  public static final String JSON_PROPERTY_CRED_VALUE = "cred_value";
  private Object credValue;

  public static final String JSON_PROPERTY_EXPANDED_TYPES = "expanded_types";
  private List<String> expandedTypes = null;

  public static final String JSON_PROPERTY_GIVEN_ID = "given_id";
  private String givenId;

  public static final String JSON_PROPERTY_ISSUER_ID = "issuer_id";
  private String issuerId;

  public static final String JSON_PROPERTY_PROOF_TYPES = "proof_types";
  private List<String> proofTypes = null;

  public static final String JSON_PROPERTY_RECORD_ID = "record_id";
  private String recordId;

  public static final String JSON_PROPERTY_SCHEMA_IDS = "schema_ids";
  private List<String> schemaIds = null;

  public static final String JSON_PROPERTY_SUBJECT_IDS = "subject_ids";
  private List<String> subjectIds = null;


  public VCRecord contexts(List<String> contexts) {
    this.contexts = contexts;
    return this;
  }

  public VCRecord addContextsItem(String contextsItem) {
    if (this.contexts == null) {
      this.contexts = new ArrayList<>();
    }
    this.contexts.add(contextsItem);
    return this;
  }

   /**
   * Get contexts
   * @return contexts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getContexts() {
    return contexts;
  }


  @JsonProperty(JSON_PROPERTY_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContexts(List<String> contexts) {
    this.contexts = contexts;
  }


  public VCRecord credTags(Map<String, String> credTags) {
    this.credTags = credTags;
    return this;
  }

  public VCRecord putCredTagsItem(String key, String credTagsItem) {
    if (this.credTags == null) {
      this.credTags = new HashMap<>();
    }
    this.credTags.put(key, credTagsItem);
    return this;
  }

   /**
   * Get credTags
   * @return credTags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRED_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getCredTags() {
    return credTags;
  }


  @JsonProperty(JSON_PROPERTY_CRED_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredTags(Map<String, String> credTags) {
    this.credTags = credTags;
  }


  public VCRecord credValue(Object credValue) {
    this.credValue = credValue;
    return this;
  }

   /**
   * (JSON-serializable) credential value
   * @return credValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(JSON-serializable) credential value")
  @JsonProperty(JSON_PROPERTY_CRED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCredValue() {
    return credValue;
  }


  @JsonProperty(JSON_PROPERTY_CRED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredValue(Object credValue) {
    this.credValue = credValue;
  }


  public VCRecord expandedTypes(List<String> expandedTypes) {
    this.expandedTypes = expandedTypes;
    return this;
  }

  public VCRecord addExpandedTypesItem(String expandedTypesItem) {
    if (this.expandedTypes == null) {
      this.expandedTypes = new ArrayList<>();
    }
    this.expandedTypes.add(expandedTypesItem);
    return this;
  }

   /**
   * Get expandedTypes
   * @return expandedTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXPANDED_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExpandedTypes() {
    return expandedTypes;
  }


  @JsonProperty(JSON_PROPERTY_EXPANDED_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpandedTypes(List<String> expandedTypes) {
    this.expandedTypes = expandedTypes;
  }


  public VCRecord givenId(String givenId) {
    this.givenId = givenId;
    return this;
  }

   /**
   * Credential identifier
   * @return givenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://example.edu/credentials/3732", value = "Credential identifier")
  @JsonProperty(JSON_PROPERTY_GIVEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGivenId() {
    return givenId;
  }


  @JsonProperty(JSON_PROPERTY_GIVEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGivenId(String givenId) {
    this.givenId = givenId;
  }


  public VCRecord issuerId(String issuerId) {
    this.issuerId = issuerId;
    return this;
  }

   /**
   * Issuer identifier
   * @return issuerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://example.edu/issuers/14", value = "Issuer identifier")
  @JsonProperty(JSON_PROPERTY_ISSUER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuerId() {
    return issuerId;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerId(String issuerId) {
    this.issuerId = issuerId;
  }


  public VCRecord proofTypes(List<String> proofTypes) {
    this.proofTypes = proofTypes;
    return this;
  }

  public VCRecord addProofTypesItem(String proofTypesItem) {
    if (this.proofTypes == null) {
      this.proofTypes = new ArrayList<>();
    }
    this.proofTypes.add(proofTypesItem);
    return this;
  }

   /**
   * Get proofTypes
   * @return proofTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROOF_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getProofTypes() {
    return proofTypes;
  }


  @JsonProperty(JSON_PROPERTY_PROOF_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProofTypes(List<String> proofTypes) {
    this.proofTypes = proofTypes;
  }


  public VCRecord recordId(String recordId) {
    this.recordId = recordId;
    return this;
  }

   /**
   * Record identifier
   * @return recordId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3fa85f64-5717-4562-b3fc-2c963f66afa6", value = "Record identifier")
  @JsonProperty(JSON_PROPERTY_RECORD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRecordId() {
    return recordId;
  }


  @JsonProperty(JSON_PROPERTY_RECORD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecordId(String recordId) {
    this.recordId = recordId;
  }


  public VCRecord schemaIds(List<String> schemaIds) {
    this.schemaIds = schemaIds;
    return this;
  }

  public VCRecord addSchemaIdsItem(String schemaIdsItem) {
    if (this.schemaIds == null) {
      this.schemaIds = new ArrayList<>();
    }
    this.schemaIds.add(schemaIdsItem);
    return this;
  }

   /**
   * Get schemaIds
   * @return schemaIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSchemaIds() {
    return schemaIds;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaIds(List<String> schemaIds) {
    this.schemaIds = schemaIds;
  }


  public VCRecord subjectIds(List<String> subjectIds) {
    this.subjectIds = subjectIds;
    return this;
  }

  public VCRecord addSubjectIdsItem(String subjectIdsItem) {
    if (this.subjectIds == null) {
      this.subjectIds = new ArrayList<>();
    }
    this.subjectIds.add(subjectIdsItem);
    return this;
  }

   /**
   * Get subjectIds
   * @return subjectIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSubjectIds() {
    return subjectIds;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectIds(List<String> subjectIds) {
    this.subjectIds = subjectIds;
  }


  /**
   * Return true if this VCRecord object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VCRecord vcRecord = (VCRecord) o;
    return Objects.equals(this.contexts, vcRecord.contexts) &&
        Objects.equals(this.credTags, vcRecord.credTags) &&
        Objects.equals(this.credValue, vcRecord.credValue) &&
        Objects.equals(this.expandedTypes, vcRecord.expandedTypes) &&
        Objects.equals(this.givenId, vcRecord.givenId) &&
        Objects.equals(this.issuerId, vcRecord.issuerId) &&
        Objects.equals(this.proofTypes, vcRecord.proofTypes) &&
        Objects.equals(this.recordId, vcRecord.recordId) &&
        Objects.equals(this.schemaIds, vcRecord.schemaIds) &&
        Objects.equals(this.subjectIds, vcRecord.subjectIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contexts, credTags, credValue, expandedTypes, givenId, issuerId, proofTypes, recordId, schemaIds, subjectIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VCRecord {\n");
    sb.append("    contexts: ").append(toIndentedString(contexts)).append("\n");
    sb.append("    credTags: ").append(toIndentedString(credTags)).append("\n");
    sb.append("    credValue: ").append(toIndentedString(credValue)).append("\n");
    sb.append("    expandedTypes: ").append(toIndentedString(expandedTypes)).append("\n");
    sb.append("    givenId: ").append(toIndentedString(givenId)).append("\n");
    sb.append("    issuerId: ").append(toIndentedString(issuerId)).append("\n");
    sb.append("    proofTypes: ").append(toIndentedString(proofTypes)).append("\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("    schemaIds: ").append(toIndentedString(schemaIds)).append("\n");
    sb.append("    subjectIds: ").append(toIndentedString(subjectIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

