/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.my_digi_id.acapy_client.model.InvitationMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InvitationRecord
 */
public class InvitationRecordTest {
    private final InvitationRecord model = new InvitationRecord();

    /**
     * Model tests for InvitationRecord
     */
    @Test
    public void testInvitationRecord() {
        // TODO: test InvitationRecord
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'inviMsgId'
     */
    @Test
    public void inviMsgIdTest() {
        // TODO: test inviMsgId
    }

    /**
     * Test the property 'invitation'
     */
    @Test
    public void invitationTest() {
        // TODO: test invitation
    }

    /**
     * Test the property 'invitationId'
     */
    @Test
    public void invitationIdTest() {
        // TODO: test invitationId
    }

    /**
     * Test the property 'invitationUrl'
     */
    @Test
    public void invitationUrlTest() {
        // TODO: test invitationUrl
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'trace'
     */
    @Test
    public void traceTest() {
        // TODO: test trace
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
