/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.my_digi_id.acapy_client.model.AMLRecord;
import io.github.my_digi_id.acapy_client.model.TAAAcceptance;
import io.github.my_digi_id.acapy_client.model.TAARecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TAAInfo
 */
public class TAAInfoTest {
    private final TAAInfo model = new TAAInfo();

    /**
     * Model tests for TAAInfo
     */
    @Test
    public void testTAAInfo() {
        // TODO: test TAAInfo
    }

    /**
     * Test the property 'amlRecord'
     */
    @Test
    public void amlRecordTest() {
        // TODO: test amlRecord
    }

    /**
     * Test the property 'taaAccepted'
     */
    @Test
    public void taaAcceptedTest() {
        // TODO: test taaAccepted
    }

    /**
     * Test the property 'taaRecord'
     */
    @Test
    public void taaRecordTest() {
        // TODO: test taaRecord
    }

    /**
     * Test the property 'taaRequired'
     */
    @Test
    public void taaRequiredTest() {
        // TODO: test taaRequired
    }

}
