/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.my_digi_id.acapy_client.model.IndyProofRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V10PresentationCreateRequestRequest
 */
public class V10PresentationCreateRequestRequestTest {
    private final V10PresentationCreateRequestRequest model = new V10PresentationCreateRequestRequest();

    /**
     * Model tests for V10PresentationCreateRequestRequest
     */
    @Test
    public void testV10PresentationCreateRequestRequest() {
        // TODO: test V10PresentationCreateRequestRequest
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'proofRequest'
     */
    @Test
    public void proofRequestTest() {
        // TODO: test proofRequest
    }

    /**
     * Test the property 'trace'
     */
    @Test
    public void traceTest() {
        // TODO: test trace
    }

}
