/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.my_digi_id.acapy_client.model.AttachDecorator;
import io.github.my_digi_id.acapy_client.model.V20PresFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V20PresProposal
 */
public class V20PresProposalTest {
    private final V20PresProposal model = new V20PresProposal();

    /**
     * Model tests for V20PresProposal
     */
    @Test
    public void testV20PresProposal() {
        // TODO: test V20PresProposal
    }

    /**
     * Test the property 'atId'
     */
    @Test
    public void atIdTest() {
        // TODO: test atId
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'formats'
     */
    @Test
    public void formatsTest() {
        // TODO: test formats
    }

    /**
     * Test the property 'proposalsTildeAttach'
     */
    @Test
    public void proposalsTildeAttachTest() {
        // TODO: test proposalsTildeAttach
    }

}
