/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.my_digi_id.acapy_client.model.DIFProofProposal;
import io.github.my_digi_id.acapy_client.model.IndyProofRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V20PresProposalByFormat
 */
public class V20PresProposalByFormatTest {
    private final V20PresProposalByFormat model = new V20PresProposalByFormat();

    /**
     * Model tests for V20PresProposalByFormat
     */
    @Test
    public void testV20PresProposalByFormat() {
        // TODO: test V20PresProposalByFormat
    }

    /**
     * Test the property 'dif'
     */
    @Test
    public void difTest() {
        // TODO: test dif
    }

    /**
     * Test the property 'indy'
     */
    @Test
    public void indyTest() {
        // TODO: test indy
    }

}
