/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.api;

import io.github.my_digi_id.acapy_client.invoker.*;
import io.github.my_digi_id.acapy_client.invoker.auth.*;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IntroductionApi
 */
public class IntroductionApiTest {

    private final IntroductionApi api = new IntroductionApi();

    /**
     * Start an introduction between two connections
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void connectionsConnIdStartIntroductionPostTest() throws ApiException {
        //String connId = null;
        //String targetConnectionId = null;
        //String message = null;
        //Object response = api.connectionsConnIdStartIntroductionPost(connId, targetConnectionId, message);
        // TODO: test validations
    }

}
