/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.api;

import io.github.my_digi_id.acapy_client.invoker.*;
import io.github.my_digi_id.acapy_client.invoker.auth.*;
import io.github.my_digi_id.acapy_client.model.PingRequest;
import io.github.my_digi_id.acapy_client.model.PingRequestResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrustpingApi
 */
public class TrustpingApiTest {

    private final TrustpingApi api = new TrustpingApi();

    /**
     * Send a trust ping to a connection
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void connectionsConnIdSendPingPostTest() throws ApiException {
        //String connId = null;
        //PingRequest body = null;
        //PingRequestResponse response = api.connectionsConnIdSendPingPost(connId, body);
        // TODO: test validations
    }

}
