/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConnectionStaticRequest
 */
public class ConnectionStaticRequestTest {
    private final ConnectionStaticRequest model = new ConnectionStaticRequest();

    /**
     * Model tests for ConnectionStaticRequest
     */
    @Test
    public void testConnectionStaticRequest() {
        // TODO: test ConnectionStaticRequest
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'myDid'
     */
    @Test
    public void myDidTest() {
        // TODO: test myDid
    }

    /**
     * Test the property 'mySeed'
     */
    @Test
    public void mySeedTest() {
        // TODO: test mySeed
    }

    /**
     * Test the property 'theirDid'
     */
    @Test
    public void theirDidTest() {
        // TODO: test theirDid
    }

    /**
     * Test the property 'theirEndpoint'
     */
    @Test
    public void theirEndpointTest() {
        // TODO: test theirEndpoint
    }

    /**
     * Test the property 'theirLabel'
     */
    @Test
    public void theirLabelTest() {
        // TODO: test theirLabel
    }

    /**
     * Test the property 'theirSeed'
     */
    @Test
    public void theirSeedTest() {
        // TODO: test theirSeed
    }

    /**
     * Test the property 'theirVerkey'
     */
    @Test
    public void theirVerkeyTest() {
        // TODO: test theirVerkey
    }

}
