/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.my_digi_id.acapy_client.model.CredentialPreview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CredentialProposal
 */
public class CredentialProposalTest {
    private final CredentialProposal model = new CredentialProposal();

    /**
     * Model tests for CredentialProposal
     */
    @Test
    public void testCredentialProposal() {
        // TODO: test CredentialProposal
    }

    /**
     * Test the property 'atId'
     */
    @Test
    public void atIdTest() {
        // TODO: test atId
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'credDefId'
     */
    @Test
    public void credDefIdTest() {
        // TODO: test credDefId
    }

    /**
     * Test the property 'credentialProposal'
     */
    @Test
    public void credentialProposalTest() {
        // TODO: test credentialProposal
    }

    /**
     * Test the property 'issuerDid'
     */
    @Test
    public void issuerDidTest() {
        // TODO: test issuerDid
    }

    /**
     * Test the property 'schemaId'
     */
    @Test
    public void schemaIdTest() {
        // TODO: test schemaId
    }

    /**
     * Test the property 'schemaIssuerDid'
     */
    @Test
    public void schemaIssuerDidTest() {
        // TODO: test schemaIssuerDid
    }

    /**
     * Test the property 'schemaName'
     */
    @Test
    public void schemaNameTest() {
        // TODO: test schemaName
    }

    /**
     * Test the property 'schemaVersion'
     */
    @Test
    public void schemaVersionTest() {
        // TODO: test schemaVersion
    }

}
