/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CredRevokedResult
 */
public class CredRevokedResultTest {
    private final CredRevokedResult model = new CredRevokedResult();

    /**
     * Model tests for CredRevokedResult
     */
    @Test
    public void testCredRevokedResult() {
        // TODO: test CredRevokedResult
    }

    /**
     * Test the property 'revoked'
     */
    @Test
    public void revokedTest() {
        // TODO: test revoked
    }

}
