/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.my_digi_id.acapy_client.model.AttachDecorator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DIDXRequest
 */
public class DIDXRequestTest {
    private final DIDXRequest model = new DIDXRequest();

    /**
     * Model tests for DIDXRequest
     */
    @Test
    public void testDIDXRequest() {
        // TODO: test DIDXRequest
    }

    /**
     * Test the property 'atId'
     */
    @Test
    public void atIdTest() {
        // TODO: test atId
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

    /**
     * Test the property 'did'
     */
    @Test
    public void didTest() {
        // TODO: test did
    }

    /**
     * Test the property 'didDocTildeAttach'
     */
    @Test
    public void didDocTildeAttachTest() {
        // TODO: test didDocTildeAttach
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

}
