/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Filter
 */
public class FilterTest {
    private final Filter model = new Filter();

    /**
     * Model tests for Filter
     */
    @Test
    public void testFilter() {
        // TODO: test Filter
    }

    /**
     * Test the property '_const'
     */
    @Test
    public void _constTest() {
        // TODO: test _const
    }

    /**
     * Test the property '_enum'
     */
    @Test
    public void _enumTest() {
        // TODO: test _enum
    }

    /**
     * Test the property 'exclusiveMaximum'
     */
    @Test
    public void exclusiveMaximumTest() {
        // TODO: test exclusiveMaximum
    }

    /**
     * Test the property 'exclusiveMinimum'
     */
    @Test
    public void exclusiveMinimumTest() {
        // TODO: test exclusiveMinimum
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'maxLength'
     */
    @Test
    public void maxLengthTest() {
        // TODO: test maxLength
    }

    /**
     * Test the property 'maximum'
     */
    @Test
    public void maximumTest() {
        // TODO: test maximum
    }

    /**
     * Test the property 'minLength'
     */
    @Test
    public void minLengthTest() {
        // TODO: test minLength
    }

    /**
     * Test the property 'minimum'
     */
    @Test
    public void minimumTest() {
        // TODO: test minimum
    }

    /**
     * Test the property 'not'
     */
    @Test
    public void notTest() {
        // TODO: test not
    }

    /**
     * Test the property 'pattern'
     */
    @Test
    public void patternTest() {
        // TODO: test pattern
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
