/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.my_digi_id.acapy_client.model.CredentialPreview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V10CredentialProposalRequestMand
 */
public class V10CredentialProposalRequestMandTest {
    private final V10CredentialProposalRequestMand model = new V10CredentialProposalRequestMand();

    /**
     * Model tests for V10CredentialProposalRequestMand
     */
    @Test
    public void testV10CredentialProposalRequestMand() {
        // TODO: test V10CredentialProposalRequestMand
    }

    /**
     * Test the property 'autoRemove'
     */
    @Test
    public void autoRemoveTest() {
        // TODO: test autoRemove
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'connectionId'
     */
    @Test
    public void connectionIdTest() {
        // TODO: test connectionId
    }

    /**
     * Test the property 'credDefId'
     */
    @Test
    public void credDefIdTest() {
        // TODO: test credDefId
    }

    /**
     * Test the property 'credentialProposal'
     */
    @Test
    public void credentialProposalTest() {
        // TODO: test credentialProposal
    }

    /**
     * Test the property 'issuerDid'
     */
    @Test
    public void issuerDidTest() {
        // TODO: test issuerDid
    }

    /**
     * Test the property 'schemaId'
     */
    @Test
    public void schemaIdTest() {
        // TODO: test schemaId
    }

    /**
     * Test the property 'schemaIssuerDid'
     */
    @Test
    public void schemaIssuerDidTest() {
        // TODO: test schemaIssuerDid
    }

    /**
     * Test the property 'schemaName'
     */
    @Test
    public void schemaNameTest() {
        // TODO: test schemaName
    }

    /**
     * Test the property 'schemaVersion'
     */
    @Test
    public void schemaVersionTest() {
        // TODO: test schemaVersion
    }

    /**
     * Test the property 'trace'
     */
    @Test
    public void traceTest() {
        // TODO: test trace
    }

}
