/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.my_digi_id.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.my_digi_id.acapy_client.model.V20Pres;
import com.my_digi_id.acapy_client.model.V20PresExRecordByFormat;
import com.my_digi_id.acapy_client.model.V20PresProposal;
import com.my_digi_id.acapy_client.model.V20PresRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V20PresExRecord
 */
public class V20PresExRecordTest {
    private final V20PresExRecord model = new V20PresExRecord();

    /**
     * Model tests for V20PresExRecord
     */
    @Test
    public void testV20PresExRecord() {
        // TODO: test V20PresExRecord
    }

    /**
     * Test the property 'autoPresent'
     */
    @Test
    public void autoPresentTest() {
        // TODO: test autoPresent
    }

    /**
     * Test the property 'byFormat'
     */
    @Test
    public void byFormatTest() {
        // TODO: test byFormat
    }

    /**
     * Test the property 'connectionId'
     */
    @Test
    public void connectionIdTest() {
        // TODO: test connectionId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'errorMsg'
     */
    @Test
    public void errorMsgTest() {
        // TODO: test errorMsg
    }

    /**
     * Test the property 'initiator'
     */
    @Test
    public void initiatorTest() {
        // TODO: test initiator
    }

    /**
     * Test the property 'pres'
     */
    @Test
    public void presTest() {
        // TODO: test pres
    }

    /**
     * Test the property 'presExId'
     */
    @Test
    public void presExIdTest() {
        // TODO: test presExId
    }

    /**
     * Test the property 'presProposal'
     */
    @Test
    public void presProposalTest() {
        // TODO: test presProposal
    }

    /**
     * Test the property 'presRequest'
     */
    @Test
    public void presRequestTest() {
        // TODO: test presRequest
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'threadId'
     */
    @Test
    public void threadIdTest() {
        // TODO: test threadId
    }

    /**
     * Test the property 'trace'
     */
    @Test
    public void traceTest() {
        // TODO: test trace
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

}
