/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.my_digi_id.acapy_client.invoker.JSON;


/**
 * CreateInvitationRequest
 */
@JsonPropertyOrder({
  CreateInvitationRequest.JSON_PROPERTY_MEDIATION_ID,
  CreateInvitationRequest.JSON_PROPERTY_METADATA,
  CreateInvitationRequest.JSON_PROPERTY_MY_LABEL,
  CreateInvitationRequest.JSON_PROPERTY_RECIPIENT_KEYS,
  CreateInvitationRequest.JSON_PROPERTY_ROUTING_KEYS,
  CreateInvitationRequest.JSON_PROPERTY_SERVICE_ENDPOINT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-12T14:46:41.984298+01:00[Europe/Berlin]")
public class CreateInvitationRequest {
  public static final String JSON_PROPERTY_MEDIATION_ID = "mediation_id";
  private String mediationId;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Object metadata;

  public static final String JSON_PROPERTY_MY_LABEL = "my_label";
  private String myLabel;

  public static final String JSON_PROPERTY_RECIPIENT_KEYS = "recipient_keys";
  private List<String> recipientKeys = null;

  public static final String JSON_PROPERTY_ROUTING_KEYS = "routing_keys";
  private List<String> routingKeys = null;

  public static final String JSON_PROPERTY_SERVICE_ENDPOINT = "service_endpoint";
  private String serviceEndpoint;


  public CreateInvitationRequest mediationId(String mediationId) {
    this.mediationId = mediationId;
    return this;
  }

   /**
   * Identifier for active mediation record to be used
   * @return mediationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3fa85f64-5717-4562-b3fc-2c963f66afa6", value = "Identifier for active mediation record to be used")
  @JsonProperty(JSON_PROPERTY_MEDIATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMediationId() {
    return mediationId;
  }


  @JsonProperty(JSON_PROPERTY_MEDIATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMediationId(String mediationId) {
    this.mediationId = mediationId;
  }


  public CreateInvitationRequest metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Optional metadata to attach to the connection created with the invitation
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional metadata to attach to the connection created with the invitation")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public CreateInvitationRequest myLabel(String myLabel) {
    this.myLabel = myLabel;
    return this;
  }

   /**
   * Optional label for connection invitation
   * @return myLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Bob", value = "Optional label for connection invitation")
  @JsonProperty(JSON_PROPERTY_MY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMyLabel() {
    return myLabel;
  }


  @JsonProperty(JSON_PROPERTY_MY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMyLabel(String myLabel) {
    this.myLabel = myLabel;
  }


  public CreateInvitationRequest recipientKeys(List<String> recipientKeys) {
    this.recipientKeys = recipientKeys;
    return this;
  }

  public CreateInvitationRequest addRecipientKeysItem(String recipientKeysItem) {
    if (this.recipientKeys == null) {
      this.recipientKeys = new ArrayList<>();
    }
    this.recipientKeys.add(recipientKeysItem);
    return this;
  }

   /**
   * List of recipient keys
   * @return recipientKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of recipient keys")
  @JsonProperty(JSON_PROPERTY_RECIPIENT_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRecipientKeys() {
    return recipientKeys;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecipientKeys(List<String> recipientKeys) {
    this.recipientKeys = recipientKeys;
  }


  public CreateInvitationRequest routingKeys(List<String> routingKeys) {
    this.routingKeys = routingKeys;
    return this;
  }

  public CreateInvitationRequest addRoutingKeysItem(String routingKeysItem) {
    if (this.routingKeys == null) {
      this.routingKeys = new ArrayList<>();
    }
    this.routingKeys.add(routingKeysItem);
    return this;
  }

   /**
   * List of routing keys
   * @return routingKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of routing keys")
  @JsonProperty(JSON_PROPERTY_ROUTING_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRoutingKeys() {
    return routingKeys;
  }


  @JsonProperty(JSON_PROPERTY_ROUTING_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoutingKeys(List<String> routingKeys) {
    this.routingKeys = routingKeys;
  }


  public CreateInvitationRequest serviceEndpoint(String serviceEndpoint) {
    this.serviceEndpoint = serviceEndpoint;
    return this;
  }

   /**
   * Connection endpoint
   * @return serviceEndpoint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://192.168.56.102:8020", value = "Connection endpoint")
  @JsonProperty(JSON_PROPERTY_SERVICE_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceEndpoint() {
    return serviceEndpoint;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceEndpoint(String serviceEndpoint) {
    this.serviceEndpoint = serviceEndpoint;
  }


  /**
   * Return true if this CreateInvitationRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateInvitationRequest createInvitationRequest = (CreateInvitationRequest) o;
    return Objects.equals(this.mediationId, createInvitationRequest.mediationId) &&
        Objects.equals(this.metadata, createInvitationRequest.metadata) &&
        Objects.equals(this.myLabel, createInvitationRequest.myLabel) &&
        Objects.equals(this.recipientKeys, createInvitationRequest.recipientKeys) &&
        Objects.equals(this.routingKeys, createInvitationRequest.routingKeys) &&
        Objects.equals(this.serviceEndpoint, createInvitationRequest.serviceEndpoint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediationId, metadata, myLabel, recipientKeys, routingKeys, serviceEndpoint);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateInvitationRequest {\n");
    sb.append("    mediationId: ").append(toIndentedString(mediationId)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    myLabel: ").append(toIndentedString(myLabel)).append("\n");
    sb.append("    recipientKeys: ").append(toIndentedString(recipientKeys)).append("\n");
    sb.append("    routingKeys: ").append(toIndentedString(routingKeys)).append("\n");
    sb.append("    serviceEndpoint: ").append(toIndentedString(serviceEndpoint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

