/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.my_digi_id.acapy_client.model.CredentialPreview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.my_digi_id.acapy_client.invoker.JSON;


/**
 * CredentialProposal
 */
@JsonPropertyOrder({
  CredentialProposal.JSON_PROPERTY_AT_ID,
  CredentialProposal.JSON_PROPERTY_AT_TYPE,
  CredentialProposal.JSON_PROPERTY_COMMENT,
  CredentialProposal.JSON_PROPERTY_CRED_DEF_ID,
  CredentialProposal.JSON_PROPERTY_CREDENTIAL_PROPOSAL,
  CredentialProposal.JSON_PROPERTY_ISSUER_DID,
  CredentialProposal.JSON_PROPERTY_SCHEMA_ID,
  CredentialProposal.JSON_PROPERTY_SCHEMA_ISSUER_DID,
  CredentialProposal.JSON_PROPERTY_SCHEMA_NAME,
  CredentialProposal.JSON_PROPERTY_SCHEMA_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-12T14:46:41.984298+01:00[Europe/Berlin]")
public class CredentialProposal {
  public static final String JSON_PROPERTY_AT_ID = "@id";
  private String atId;

  public static final String JSON_PROPERTY_AT_TYPE = "@type";
  private String atType;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private JsonNullable<String> comment = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CRED_DEF_ID = "cred_def_id";
  private String credDefId;

  public static final String JSON_PROPERTY_CREDENTIAL_PROPOSAL = "credential_proposal";
  private CredentialPreview credentialProposal;

  public static final String JSON_PROPERTY_ISSUER_DID = "issuer_did";
  private String issuerDid;

  public static final String JSON_PROPERTY_SCHEMA_ID = "schema_id";
  private String schemaId;

  public static final String JSON_PROPERTY_SCHEMA_ISSUER_DID = "schema_issuer_did";
  private String schemaIssuerDid;

  public static final String JSON_PROPERTY_SCHEMA_NAME = "schema_name";
  private String schemaName;

  public static final String JSON_PROPERTY_SCHEMA_VERSION = "schema_version";
  private String schemaVersion;


  public CredentialProposal atId(String atId) {
    this.atId = atId;
    return this;
  }

   /**
   * Message identifier
   * @return atId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3fa85f64-5717-4562-b3fc-2c963f66afa6", value = "Message identifier")
  @JsonProperty(JSON_PROPERTY_AT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAtId() {
    return atId;
  }


  @JsonProperty(JSON_PROPERTY_AT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAtId(String atId) {
    this.atId = atId;
  }


   /**
   * Message type
   * @return atType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://didcomm.org/my-family/1.0/my-message-type", value = "Message type")
  @JsonProperty(JSON_PROPERTY_AT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAtType() {
    return atType;
  }




  public CredentialProposal comment(String comment) {
    this.comment = JsonNullable.<String>of(comment);
    return this;
  }

   /**
   * Human-readable comment
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Human-readable comment")
  @JsonIgnore

  public String getComment() {
        return comment.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getComment_JsonNullable() {
    return comment;
  }
  
  @JsonProperty(JSON_PROPERTY_COMMENT)
  public void setComment_JsonNullable(JsonNullable<String> comment) {
    this.comment = comment;
  }

  public void setComment(String comment) {
    this.comment = JsonNullable.<String>of(comment);
  }


  public CredentialProposal credDefId(String credDefId) {
    this.credDefId = credDefId;
    return this;
  }

   /**
   * Get credDefId
   * @return credDefId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv:3:CL:20:tag", value = "")
  @JsonProperty(JSON_PROPERTY_CRED_DEF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCredDefId() {
    return credDefId;
  }


  @JsonProperty(JSON_PROPERTY_CRED_DEF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredDefId(String credDefId) {
    this.credDefId = credDefId;
  }


  public CredentialProposal credentialProposal(CredentialPreview credentialProposal) {
    this.credentialProposal = credentialProposal;
    return this;
  }

   /**
   * Get credentialProposal
   * @return credentialProposal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREDENTIAL_PROPOSAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CredentialPreview getCredentialProposal() {
    return credentialProposal;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIAL_PROPOSAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredentialProposal(CredentialPreview credentialProposal) {
    this.credentialProposal = credentialProposal;
  }


  public CredentialProposal issuerDid(String issuerDid) {
    this.issuerDid = issuerDid;
    return this;
  }

   /**
   * Get issuerDid
   * @return issuerDid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv", value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuerDid() {
    return issuerDid;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerDid(String issuerDid) {
    this.issuerDid = issuerDid;
  }


  public CredentialProposal schemaId(String schemaId) {
    this.schemaId = schemaId;
    return this;
  }

   /**
   * Get schemaId
   * @return schemaId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv:2:schema_name:1.0", value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaId() {
    return schemaId;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaId(String schemaId) {
    this.schemaId = schemaId;
  }


  public CredentialProposal schemaIssuerDid(String schemaIssuerDid) {
    this.schemaIssuerDid = schemaIssuerDid;
    return this;
  }

   /**
   * Get schemaIssuerDid
   * @return schemaIssuerDid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WgWxqztrNooG92RXvxSTWv", value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaIssuerDid() {
    return schemaIssuerDid;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_ISSUER_DID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaIssuerDid(String schemaIssuerDid) {
    this.schemaIssuerDid = schemaIssuerDid;
  }


  public CredentialProposal schemaName(String schemaName) {
    this.schemaName = schemaName;
    return this;
  }

   /**
   * Get schemaName
   * @return schemaName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaName() {
    return schemaName;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaName(String schemaName) {
    this.schemaName = schemaName;
  }


  public CredentialProposal schemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.0", value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaVersion() {
    return schemaVersion;
  }


  @JsonProperty(JSON_PROPERTY_SCHEMA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
  }


  /**
   * Return true if this CredentialProposal object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialProposal credentialProposal = (CredentialProposal) o;
    return Objects.equals(this.atId, credentialProposal.atId) &&
        Objects.equals(this.atType, credentialProposal.atType) &&
        Objects.equals(this.comment, credentialProposal.comment) &&
        Objects.equals(this.credDefId, credentialProposal.credDefId) &&
        Objects.equals(this.credentialProposal, credentialProposal.credentialProposal) &&
        Objects.equals(this.issuerDid, credentialProposal.issuerDid) &&
        Objects.equals(this.schemaId, credentialProposal.schemaId) &&
        Objects.equals(this.schemaIssuerDid, credentialProposal.schemaIssuerDid) &&
        Objects.equals(this.schemaName, credentialProposal.schemaName) &&
        Objects.equals(this.schemaVersion, credentialProposal.schemaVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atId, atType, comment, credDefId, credentialProposal, issuerDid, schemaId, schemaIssuerDid, schemaName, schemaVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialProposal {\n");
    sb.append("    atId: ").append(toIndentedString(atId)).append("\n");
    sb.append("    atType: ").append(toIndentedString(atType)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    credDefId: ").append(toIndentedString(credDefId)).append("\n");
    sb.append("    credentialProposal: ").append(toIndentedString(credentialProposal)).append("\n");
    sb.append("    issuerDid: ").append(toIndentedString(issuerDid)).append("\n");
    sb.append("    schemaId: ").append(toIndentedString(schemaId)).append("\n");
    sb.append("    schemaIssuerDid: ").append(toIndentedString(schemaIssuerDid)).append("\n");
    sb.append("    schemaName: ").append(toIndentedString(schemaName)).append("\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

