/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.my_digi_id.acapy_client.invoker.JSON;


/**
 * IndyProofRequestedProofRevealedAttr
 */
@JsonPropertyOrder({
  IndyProofRequestedProofRevealedAttr.JSON_PROPERTY_ENCODED,
  IndyProofRequestedProofRevealedAttr.JSON_PROPERTY_RAW,
  IndyProofRequestedProofRevealedAttr.JSON_PROPERTY_SUB_PROOF_INDEX
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-12T14:46:41.984298+01:00[Europe/Berlin]")
public class IndyProofRequestedProofRevealedAttr {
  public static final String JSON_PROPERTY_ENCODED = "encoded";
  private String encoded;

  public static final String JSON_PROPERTY_RAW = "raw";
  private String raw;

  public static final String JSON_PROPERTY_SUB_PROOF_INDEX = "sub_proof_index";
  private Integer subProofIndex;


  public IndyProofRequestedProofRevealedAttr encoded(String encoded) {
    this.encoded = encoded;
    return this;
  }

   /**
   * Encoded value
   * @return encoded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Encoded value")
  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncoded() {
    return encoded;
  }


  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoded(String encoded) {
    this.encoded = encoded;
  }


  public IndyProofRequestedProofRevealedAttr raw(String raw) {
    this.raw = raw;
    return this;
  }

   /**
   * Raw value
   * @return raw
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Raw value")
  @JsonProperty(JSON_PROPERTY_RAW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRaw() {
    return raw;
  }


  @JsonProperty(JSON_PROPERTY_RAW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRaw(String raw) {
    this.raw = raw;
  }


  public IndyProofRequestedProofRevealedAttr subProofIndex(Integer subProofIndex) {
    this.subProofIndex = subProofIndex;
    return this;
  }

   /**
   * Sub-proof index
   * @return subProofIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sub-proof index")
  @JsonProperty(JSON_PROPERTY_SUB_PROOF_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSubProofIndex() {
    return subProofIndex;
  }


  @JsonProperty(JSON_PROPERTY_SUB_PROOF_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubProofIndex(Integer subProofIndex) {
    this.subProofIndex = subProofIndex;
  }


  /**
   * Return true if this IndyProofRequestedProofRevealedAttr object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndyProofRequestedProofRevealedAttr indyProofRequestedProofRevealedAttr = (IndyProofRequestedProofRevealedAttr) o;
    return Objects.equals(this.encoded, indyProofRequestedProofRevealedAttr.encoded) &&
        Objects.equals(this.raw, indyProofRequestedProofRevealedAttr.raw) &&
        Objects.equals(this.subProofIndex, indyProofRequestedProofRevealedAttr.subProofIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encoded, raw, subProofIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndyProofRequestedProofRevealedAttr {\n");
    sb.append("    encoded: ").append(toIndentedString(encoded)).append("\n");
    sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
    sb.append("    subProofIndex: ").append(toIndentedString(subProofIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

