/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.my_digi_id.acapy_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.my_digi_id.acapy_client.model.IndyEQProof;
import io.github.my_digi_id.acapy_client.model.IndyGEProof;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.my_digi_id.acapy_client.invoker.JSON;


/**
 * IndyPrimaryProof
 */
@JsonPropertyOrder({
  IndyPrimaryProof.JSON_PROPERTY_EQ_PROOF,
  IndyPrimaryProof.JSON_PROPERTY_GE_PROOFS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-12T14:46:41.984298+01:00[Europe/Berlin]")
public class IndyPrimaryProof {
  public static final String JSON_PROPERTY_EQ_PROOF = "eq_proof";
  private JsonNullable<IndyEQProof> eqProof = JsonNullable.<IndyEQProof>undefined();

  public static final String JSON_PROPERTY_GE_PROOFS = "ge_proofs";
  private JsonNullable<List<IndyGEProof>> geProofs = JsonNullable.<List<IndyGEProof>>undefined();


  public IndyPrimaryProof eqProof(IndyEQProof eqProof) {
    this.eqProof = JsonNullable.<IndyEQProof>of(eqProof);
    return this;
  }

   /**
   * Indy equality proof
   * @return eqProof
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indy equality proof")
  @JsonIgnore

  public IndyEQProof getEqProof() {
        return eqProof.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EQ_PROOF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<IndyEQProof> getEqProof_JsonNullable() {
    return eqProof;
  }
  
  @JsonProperty(JSON_PROPERTY_EQ_PROOF)
  public void setEqProof_JsonNullable(JsonNullable<IndyEQProof> eqProof) {
    this.eqProof = eqProof;
  }

  public void setEqProof(IndyEQProof eqProof) {
    this.eqProof = JsonNullable.<IndyEQProof>of(eqProof);
  }


  public IndyPrimaryProof geProofs(List<IndyGEProof> geProofs) {
    this.geProofs = JsonNullable.<List<IndyGEProof>>of(geProofs);
    return this;
  }

  public IndyPrimaryProof addGeProofsItem(IndyGEProof geProofsItem) {
    if (this.geProofs == null || !this.geProofs.isPresent()) {
      this.geProofs = JsonNullable.<List<IndyGEProof>>of(new ArrayList<>());
    }
    try {
      this.geProofs.get().add(geProofsItem);
    } catch (NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Indy GE proofs
   * @return geProofs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indy GE proofs")
  @JsonIgnore

  public List<IndyGEProof> getGeProofs() {
        return geProofs.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GE_PROOFS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<IndyGEProof>> getGeProofs_JsonNullable() {
    return geProofs;
  }
  
  @JsonProperty(JSON_PROPERTY_GE_PROOFS)
  public void setGeProofs_JsonNullable(JsonNullable<List<IndyGEProof>> geProofs) {
    this.geProofs = geProofs;
  }

  public void setGeProofs(List<IndyGEProof> geProofs) {
    this.geProofs = JsonNullable.<List<IndyGEProof>>of(geProofs);
  }


  /**
   * Return true if this IndyPrimaryProof object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndyPrimaryProof indyPrimaryProof = (IndyPrimaryProof) o;
    return Objects.equals(this.eqProof, indyPrimaryProof.eqProof) &&
        Objects.equals(this.geProofs, indyPrimaryProof.geProofs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eqProof, geProofs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndyPrimaryProof {\n");
    sb.append("    eqProof: ").append(toIndentedString(eqProof)).append("\n");
    sb.append("    geProofs: ").append(toIndentedString(geProofs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

