/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClaimFormat
 */
public class ClaimFormatTest {
    private final ClaimFormat model = new ClaimFormat();

    /**
     * Model tests for ClaimFormat
     */
    @Test
    public void testClaimFormat() {
        // TODO: test ClaimFormat
    }

    /**
     * Test the property 'jwt'
     */
    @Test
    public void jwtTest() {
        // TODO: test jwt
    }

    /**
     * Test the property 'jwtVc'
     */
    @Test
    public void jwtVcTest() {
        // TODO: test jwtVc
    }

    /**
     * Test the property 'jwtVp'
     */
    @Test
    public void jwtVpTest() {
        // TODO: test jwtVp
    }

    /**
     * Test the property 'ldp'
     */
    @Test
    public void ldpTest() {
        // TODO: test ldp
    }

    /**
     * Test the property 'ldpVc'
     */
    @Test
    public void ldpVcTest() {
        // TODO: test ldpVc
    }

    /**
     * Test the property 'ldpVp'
     */
    @Test
    public void ldpVpTest() {
        // TODO: test ldpVp
    }

}
