/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IndyCredInfo
 */
public class IndyCredInfoTest {
    private final IndyCredInfo model = new IndyCredInfo();

    /**
     * Model tests for IndyCredInfo
     */
    @Test
    public void testIndyCredInfo() {
        // TODO: test IndyCredInfo
    }

    /**
     * Test the property 'attrs'
     */
    @Test
    public void attrsTest() {
        // TODO: test attrs
    }

    /**
     * Test the property 'credDefId'
     */
    @Test
    public void credDefIdTest() {
        // TODO: test credDefId
    }

    /**
     * Test the property 'credRevId'
     */
    @Test
    public void credRevIdTest() {
        // TODO: test credRevId
    }

    /**
     * Test the property 'referent'
     */
    @Test
    public void referentTest() {
        // TODO: test referent
    }

    /**
     * Test the property 'revRegId'
     */
    @Test
    public void revRegIdTest() {
        // TODO: test revRegId
    }

    /**
     * Test the property 'schemaId'
     */
    @Test
    public void schemaIdTest() {
        // TODO: test schemaId
    }

}
