/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ibm.ssi.acapy_client.model.IndyProofIdentifier;
import com.ibm.ssi.acapy_client.model.IndyProofProof;
import com.ibm.ssi.acapy_client.model.IndyProofRequestedProof;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IndyProof
 */
public class IndyProofTest {
    private final IndyProof model = new IndyProof();

    /**
     * Model tests for IndyProof
     */
    @Test
    public void testIndyProof() {
        // TODO: test IndyProof
    }

    /**
     * Test the property 'identifiers'
     */
    @Test
    public void identifiersTest() {
        // TODO: test identifiers
    }

    /**
     * Test the property 'proof'
     */
    @Test
    public void proofTest() {
        // TODO: test proof
    }

    /**
     * Test the property 'requestedProof'
     */
    @Test
    public void requestedProofTest() {
        // TODO: test requestedProof
    }

}
