/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ibm.ssi.acapy_client.model.IndyProofProofAggregatedProof;
import com.ibm.ssi.acapy_client.model.IndyProofProofProofsProof;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IndyProofProof
 */
public class IndyProofProofTest {
    private final IndyProofProof model = new IndyProofProof();

    /**
     * Model tests for IndyProofProof
     */
    @Test
    public void testIndyProofProof() {
        // TODO: test IndyProofProof
    }

    /**
     * Test the property 'aggregatedProof'
     */
    @Test
    public void aggregatedProofTest() {
        // TODO: test aggregatedProof
    }

    /**
     * Test the property 'proofs'
     */
    @Test
    public void proofsTest() {
        // TODO: test proofs
    }

}
