/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RevokeRequest
 */
public class RevokeRequestTest {
    private final RevokeRequest model = new RevokeRequest();

    /**
     * Model tests for RevokeRequest
     */
    @Test
    public void testRevokeRequest() {
        // TODO: test RevokeRequest
    }

    /**
     * Test the property 'credExId'
     */
    @Test
    public void credExIdTest() {
        // TODO: test credExId
    }

    /**
     * Test the property 'credRevId'
     */
    @Test
    public void credRevIdTest() {
        // TODO: test credRevId
    }

    /**
     * Test the property 'publish'
     */
    @Test
    public void publishTest() {
        // TODO: test publish
    }

    /**
     * Test the property 'revRegId'
     */
    @Test
    public void revRegIdTest() {
        // TODO: test revRegId
    }

}
