/*
 * IBM-Deutschland
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.ssi.acapy_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ibm.ssi.acapy_client.model.V20CredExRecord;
import com.ibm.ssi.acapy_client.model.V20CredExRecordIndy;
import com.ibm.ssi.acapy_client.model.V20CredExRecordLDProof;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V20CredExRecordDetail
 */
public class V20CredExRecordDetailTest {
    private final V20CredExRecordDetail model = new V20CredExRecordDetail();

    /**
     * Model tests for V20CredExRecordDetail
     */
    @Test
    public void testV20CredExRecordDetail() {
        // TODO: test V20CredExRecordDetail
    }

    /**
     * Test the property 'credExRecord'
     */
    @Test
    public void credExRecordTest() {
        // TODO: test credExRecord
    }

    /**
     * Test the property 'indy'
     */
    @Test
    public void indyTest() {
        // TODO: test indy
    }

    /**
     * Test the property 'ldProof'
     */
    @Test
    public void ldProofTest() {
        // TODO: test ldProof
    }

}
